// Objective-C API for talking to github.com/lightningnetwork/lnd/mobile Go package.
//   gobind -lang=objc github.com/lightningnetwork/lnd/mobile
//
// File is generated by gobind. Do not edit.

#ifndef __Lndbindings_H__
#define __Lndbindings_H__

@import Foundation;
#include "Universe.objc.h"


FOUNDATION_EXPORT void LndbindingsStart(NSString* appDir);

#endif
